### ISSUE TITLE
Status of card rendering 

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/joust#51]
Thoughts on card rendering and game tags

## "Full" card frame (Sunwell)
* [x] `CLASS` (frame color)
* [x] `PREMIUM` (golden cards - "real" golden mode + "simple" golden mode, eg. golden frame with no animations) - HearthSim/sunwell#6
* [x] `RARITY` (gem)
* [x] `CARD_SET` (`CORE` is no gem)
* [x] `RACE`
* [x] `COST`
* [x] `ATK`, `HEALTH`, `DURABILITY`
* [x] `SILENCED`(text crossed out)
* [x] `ELITE` (dragon)
* [x] `SPELLS_COST_HEALTH` - HearthSim/sunwell#5
* [x] `SHIFTING` (Shifter Zerus) - HearthSim/sunwell#11

## Card text
* [ ] `CURRENT_HEROPOWER_DAMAGE_BONUS` (from Fallen Hero)
* [ ] `HERO_POWER_DOUBLE`
* [x] `SPELLPOWER_DOUBLE`
* [x] `RECEIVES_DOUBLE_SPELLDAMAGE_BONUS` (Arcane Blast)

## Card Glows
* [x] Playable
* [x] `COMBO` (with `COMBO_ACTIVE` on the player)
* [x] `POWERED_UP` (orange glow)
* [x] `EVIL_GLOW` (Chromaggus/Rafaam... player + opponent)

## In-play

Tracking in #7

## Misc
* How to attach buffs?
* Buff text?
* Copied deathrattles modify the buff text
* "green" / "red" text for buffed/damaged minions (eg. reference defaults)
* `DISPLAYED_CREATOR` is a thing

## Custom hooks?
* ~~Could do custom things eg. display a skull on `TO_BE_DESTROYED` cards~~

**Comment by andburn** [comment]
What format would be preferred? A separate react project or an npm module?

**Comment by jleclanche** [comment]
That'll be up to @beheh

**Comment by beheh** [comment]
Definitely a React component. I'm a bit concerned because this will mean getting all the Art out, including Heroes and Hero Powers, and all of these things have a dependency on the Joust Entity class right now. We'll have to make them much more parameterizable, and maybe make a package out of the Typescript enums.

This may also include the stats, which are currently outside of the the actual card renderer component. I'll have to think about where we do the actual cut.

**Comment by jleclanche** [comment]
Joust can depend on the card renderer, and rely on it for all the texturing and stuff. It sounds like a much better idea in fact.

**Comment by beheh** [comment]
It's the opposite problem: the card renderer currently depends on Joust's `Entity` (and various other props, like card metadata). We'll have to modularize the components further (for example, to expect specific status effects as boolean values as opposed to passing all tags, or outsource the TypeScript enums).

**Comment by jleclanche** [comment]
> the card renderer currently depends on Joust's Entity

I see why it would, but it shouldn't. The basic API a card renderer should have is the creation of a "Card" object with just an ID and a dictionary of tags. The renderer then looks at all the relevant tags to render the entity and you can get, from that entity, a render of various types ("on-board" minion portrait, in-hand, ...).

**Comment by beheh** [comment]
Yeah, it's not hard to change. It just takes quite some time (outsourcing the enums+generator, figuring out a way to include the CSS...), and I haven't got that time right now. There's also other smaller dependencies, like Drag-and-drop for Kettle, Stats should probably be moved inside the card renderer and other stuff.

**Comment by jleclanche** [comment]
Thoughts on card rendering and game tags

## "Full" card frame
* [ ] `CLASS` (frame color)
* [ ] `PREMIUM` (golden cards - "real" golden mode + "simple" golden mode, eg. golden frame with no animations)
* [ ] `RARITY` (gem)
* [ ] `CARD_SET` (`CORE` is no gem)
* [ ] `RACE`
* [ ] `COST`
* [ ] `ATK`, `HEALTH`, `DURABILITY`
* [ ] `SILENCED`(text crossed out)
* [ ] `ELITE` (dragon)

## "Minion" style (on-board)
* [ ] `ELITE` (dragon)
* [ ] `NUM_TURNS_IN_PLAY` + `CHARGE` (for summoning sickness)
* [ ] `TRIGGER_VISUAL``DEATHRATTLE`, `INSPIRE`, `POISONOUS` (+ flashing upon trigger? how?)
* [ ] `TAUNT`, `DIVINE_SHIELD`, `STEALTH`
* [ ] `WINDFURY` (animated?), `AURA` (animated?)
* [ ] `SILENCED`, `ENRAGED`
* [ ] `CANT_BE_TARGETED_BY_ABILITIES` (Chromatic Dragonkin)
* [ ] `HEAVILY_ARMORED` (Animated Armor effect for League adventure)

## "Hero" style
* [ ] `TAUNT`
* [ ] `HEAVILY_ARMORED` (Animated Armor)

## Card text
* [ ] `CURRENT_HEROPOWER_DAMAGE_BONUS` (from Fallen Hero)
* [ ] `HERO_POWER_DOUBLE`
* [ ] `SPELLPOWER_DOUBLE`
* [ ] `RECEIVES_DOUBLE_SPELLDAMAGE_BONUS` (Arcane Blast)

## Misc
* How to attach buffs?
* Buff text?
* Copied deathrattles modify the buff text
* "green" / "red" text for buffed/damaged minions (eg. reference defaults)
* Card glow: Playable (available in options), `COMBO` with `COMBO_ACTIVE` on the player, `POWERED_UP` (orange glow), `EVIL_GLOW` for bad cards...
* `DISPLAYED_CREATOR` is a thing

## Custom hooks?
* Could do custom things eg. display a skull on `TO_BE_DESTROYED` cards

**Comment by jleclanche** [comment]
I'm not sure if `AFFECTED_BY_SPELL_POWER` is *always* on cards affected by spell power or not... if it is, it could affect quite a few things.

**Comment by jleclanche** [comment]
Closing this as the card renderer we have right now is good enough. Moving to sunwell will be another matter.
