### ISSUE TITLE
[Meta] High priority tasks

### ISSUE THREAD

**Issue by beheh** [HearthSim/joust#70]
In descending priority:

1. [x] Fix text on minions
2. ~~Hero/Weapon/Hero power centering~~
3. [x] Deck (replace with flipped card)
4. [x] EndTurn button (fix text size)
5. [x] Land choices branch - #66
6. [ ] Turn Indicator - #10
7. [x] End of game visuals (crater)
8. [x] Switch to card art JPGs for now
9. [x] Display cards played - #5

**Comment by Epix37** [comment]
Also need to switch to jpgs instead of pngs.

Not only does that help increase loading times but also fixes the issues with cards like Voidwalker:
http://static.hsreplay.net/static/joust/textures/W6_117_D.png
http://static.hsreplay.net/static/joust/textures/W6_117_D.jpg

**Comment by jleclanche** [comment]
I don't think the Voidcaller issue is related to jpg/png. Just an ordering issue.

**Comment by Epix37** [comment]
While that might be true, the issue is irrelevant when using jpgs, which we should anyway.

**Comment by jleclanche** [comment]
I don't think it's irrelevant using JPGs, I think that voidcaller just got lucky when converted.

**Comment by Epix37** [comment]
Power Overwhelming: [png](http://static.hsreplay.net/static/joust/textures/W7_129_D.png), [jpg](http://static.hsreplay.net/static/joust/textures/W7_129_D.jpg)
Flame Imp: [png](http://static.hsreplay.net/static/joust/textures/W7_009_D.png), [jpg](http://static.hsreplay.net/static/joust/textures/W7_009_D.jpg)
Soul Fire: [png](http://static.hsreplay.net/static/joust/textures/W9_A118_D.png), [jpg](http://static.hsreplay.net/static/joust/textures/W9_A118_D.jpg)
Mirror Image: [png](http://static.hsreplay.net/static/joust/textures/W10_A191_D.png), [jpg](http://static.hsreplay.net/static/joust/textures/W10_A191_D.jpg)

**Comment by andburn** [comment]
Lots of the art images have alpha channels, jpgs are just cutting that out.

**Comment by jleclanche** [comment]
Seriously? How are you generating the jpgs?

**Comment by jleclanche** [comment]
Closing. The turn indicator isnt an issue anymore with the new layout.
